name: Build Chain

on: [pull_request]

jobs:
  build-chain:
    strategy:
      matrix:
        java-version: [8, 11]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: Free disk space
        run: |
          df -h
          sudo apt-get remove aria2 -yq >/dev/null 2>&1
          df -h      
                            
